//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by GitVersion.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0+1.Branch.master.Sha.8a2feb414aac8df03aa63335bc756d2c6d5c6236")]
