//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by GitVersion.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0+Branch.master.Sha.fdc04f3a152baeea71847ae52065f323b2536b2b")]
